#!/usr/bin/env python
# This copy of GrowlVoice has been patched with https://github.com/szhu/fix-growlvoice.
# See the repo for more infomation.

from os.path import join, split
from sys import argv, stderr
from subprocess import Popen, PIPE
# from time import sleep

gv_path = join(split(argv[0])[0], 'GrowlVoice')
gv = Popen([gv_path], stderr=PIPE)

injected = False

while True:
	line = gv.stderr.readline()
	if not injected and 'Automatically Signing In...' in line:
		print 'fix_growlvoice: triggering inject'
		nc = Popen(['nc', '-U', '/Library/Application Support/GrowlVoice/socket'], stdin=PIPE)
		nc.stdin.write(str(gv.pid) + '\n')
		nc.stdin.close()
		nc.wait()
		print 'fix_growlvoice: finished inject'

		# # Something like this may be needed to prevent race conditions
		# kill_stop = Popen(['/usr/bin/env', 'kill', '-TSTP', str(gv.pid)])
		# kill_stop.wait()
		# print 'fix_growlvoice: sleep'
		# sleep(1)
		# print 'fix_growlvoice: endsleep'
		# kill_cont = Popen(['/usr/bin/env', 'kill', '-CONT', str(gv.pid)])

		injected = True
	if line == '': break
	stderr.write(line)

gv.wait()
